channels:
- conda-forge
dependencies:
- jupyterlab=0.33.6
- nodejs=8.11.3
- notebook=5.4
- nbconvert=5.3
- ipykernel=4.7
- ipywidgets=7.2
- widgetsnbextension=3.2
- pandas=0.23
- python=3.6
- scikit-image=0.13
- scikit-learn=0.18
- seaborn=0.7
- sympy=1.0
- Pillow=5.1.0
- matplotlib=2.2.2