version: '3.3'

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            # Password for root access
            MYSQL_ROOT_PASSWORD: test123
            MYSQL_DATABASE: test_db
            # So you don't have to use root, but you can if you like
            MYSQL_USER: test_user
            # You can use whatever password you like
            MYSQL_PASSWORD: test_password
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '9001:3306'
        expose:
            # Opens port 9001 on the container
            - '9001'